# Name of your workflow.
name: flutter drive

# Trigger the workflow on push or pull request.
on: [push, pull_request]
jobs:
  instrumentation-tests:
    name: Instrumentation tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: true
      matrix:
        # API 21 is flaky and times out.
        api-level: [30]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 11
      # - run: ./ci_clear_gradle_cache.sh
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/**.gradle.kts', '**/gradle/wrapper/gradle-wrapper.properties', '**/buildSrc/src/main/kotlin/Library.kt') }}

      # API 30+ emulators only have Google API system images.
      - name: Get AVD target
        uses: ./.github/actions/get-avd-target
        id: avd-target
        with:
          api-level: ${{ matrix.api-level }}

      # Retrieve the cached emulator snapshot.
      - uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}-${{ steps.avd-target.outputs.target }}
      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ steps.avd-target.outputs.target }}
          disable-animations: true
          force-avd-creation: true
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot-save
          # script: |
          #     flutter pub get
          #     flutter drive  --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d ${{ matrix.api-level }}
      - name: Run tests
        uses: subosito/flutter-action@master
        with:
          channel: "stable"
      - run: flutter pub get
